### PR TITLE
Exercise files for Git homework part 2

### PR DESCRIPTION
**Pull request by catalina-tech**

### CODE REVIEW

**Review by jason-vasilev — COMMENTED** [review]
I see you've push the 3 files in one commit. Steps 6, 7, and 8 were requiring that each file is pushed in it's own commit, so you could practice staging for commit individual files. Could you make a few changes to the files and push them in separate commits? You can also update the PR by adding description text, explaining what is overall done or added to the main branch. For example "Exercise files for Git homework part 2."

**Review by rekamadacsi — APPROVED** [review]
Good job! However, all the changes are in one commit instead of three separate commits. The proposal was to practice selecting files one by one and committing them separately, but it's still okay. 
You can merge your PR :)

**Comment by catalina-tech** [comment]
> _ No description provided. _
Hello!! Thank you so much for your feedback Jason and Reka, I made some changes in each file and did the commit of each file individually as you can see here https://github.com/catalina-tech/hyf-homework/pull/2/commits. :)

**Review by jason-vasilev — APPROVED** [review]
Thank you, Catalina. You are welcome to merge it ☺️

**Pull request merged**
